version: '3.5'

services:
  mdid:
    build: ../.
    image: wmit/mdid:3.5
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    depends_on:
      - solr
      - rabbitmq
      - memcached
      - database
    environment:
      DB_USER: mdid
      DB_PASSWORD: supersecretpassword
      DB_NAME: mdid
  worker:
    build: ../.
    image: wmit/mdid:3.5
    command: python manage.py runworkers
    healthcheck:
      disable: true
    depends_on:
      - solr
      - rabbitmq
      - memcached
      - database
  solr:
    image: solr:7.7.3-slim
  rabbitmq:
    image: rabbitmq:3.8-alpine
  memcached:
    image: memcached:1.6-alpine
    command: memcached -m 128
  database:
    image: mysql:5.7
    healthcheck:
      test: mysql -umdid -psupersecretpassword mdid -e'SELECT 1'
    environment:
      MYSQL_DATABASE: mdid
      MYSQL_USER: mdid
      MYSQL_PASSWORD: supersecretpassword
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
